[package]
name = "webtransport-generic"
description = "Generic trait to implement a webtransport API"
authors = ["Luke Curley", "François Michel"]
repository = "https://github.com/kixelated/webtransport-rs"
license = "MIT OR Apache-2.0"

version = "0.6.0"
edition = "2021"

keywords = ["quic", "http3", "webtransport"]
categories = ["network-programming", "web-programming"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
thiserror = "1"
anyhow = "1"
bytes = "1"
tokio = { version = "1", default-features = false }
trait-variant = "0.1"
