[package]
name = "web-transport"
description = "WebTransport client and server - Placeholder"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/webtransport-rs"
license = "MIT"

version = "0.10.0"
edition = "2021"

keywords = ["quic", "http3", "webtransport"]
categories = ["network-programming", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-transport-quinn = { version = "0.10", path = "../web-transport-quinn" }
bytes = "1"
thiserror = "1"
