name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Install Rust with clippy/rustfmt
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      # Make sure u guys don't write bad code
      - run: cargo test --verbose
      - run: cargo clippy --no-deps
      - run: cargo fmt --check

      # Check for unused dependencies
      - uses: bnjbvr/cargo-machete@main
